language : c
compiler :
  - gcc
  - clang
before_install :
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcunit1-dev
  - sudo pip install cpp-coveralls
script :
  - CFLAGS=--coverage LDFLAGS=--coverage make
  - CFLAGS=--coverage LDFLAGS=--coverage make --quiet test
after_success:
  - coveralls --exclude test --gcov-options '\-lp'
